package com.markscottwright.adventofcode2019;

import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.Set;

public class Day6 {
    // @formatter:off
    final static String INPUT = 
        "RN2)HSX\r\n" + 
        "TYQ)JFL\r\n" + 
        "PBD)P1X\r\n" + 
        "69L)R17\r\n" + 
        "LWG)VPQ\r\n" + 
        "TL1)MC6\r\n" + 
        "LV4)LFV\r\n" + 
        "LGY)LF3\r\n" + 
        "Y8D)CMZ\r\n" + 
        "N5F)CR9\r\n" + 
        "C6M)J97\r\n" + 
        "M39)BZP\r\n" + 
        "MNY)8NQ\r\n" + 
        "NVF)HXQ\r\n" + 
        "FKJ)KP3\r\n" + 
        "5YR)87D\r\n" + 
        "CYL)677\r\n" + 
        "JPT)ZL6\r\n" + 
        "79B)J1Q\r\n" + 
        "JYH)TS6\r\n" + 
        "LJN)QY3\r\n" + 
        "61T)YKQ\r\n" + 
        "3CM)8DT\r\n" + 
        "6FM)D8L\r\n" + 
        "TJ5)G4G\r\n" + 
        "1KL)BGT\r\n" + 
        "371)95C\r\n" + 
        "7VQ)241\r\n" + 
        "GWX)KNY\r\n" + 
        "7NS)VYG\r\n" + 
        "N5J)9K1\r\n" + 
        "VH9)Q3H\r\n" + 
        "4SL)JRQ\r\n" + 
        "6VB)Z96\r\n" + 
        "Z68)YY6\r\n" + 
        "RHD)S1K\r\n" + 
        "FP5)XJH\r\n" + 
        "BWC)98G\r\n" + 
        "JKT)PTH\r\n" + 
        "YKL)THM\r\n" + 
        "TJJ)BXL\r\n" + 
        "VM9)LV1\r\n" + 
        "W8C)P7R\r\n" + 
        "C5J)8SL\r\n" + 
        "7DG)RN2\r\n" + 
        "JQD)KXN\r\n" + 
        "C53)DX6\r\n" + 
        "RST)4DP\r\n" + 
        "652)FG6\r\n" + 
        "1PB)CCQ\r\n" + 
        "KY5)HBS\r\n" + 
        "J68)GZT\r\n" + 
        "GMJ)WLX\r\n" + 
        "ZM1)DFF\r\n" + 
        "38F)S9G\r\n" + 
        "869)TYQ\r\n" + 
        "534)H7C\r\n" + 
        "BXH)YQV\r\n" + 
        "FNP)15P\r\n" + 
        "YKK)F27\r\n" + 
        "925)HTT\r\n" + 
        "1FD)J77\r\n" + 
        "8RN)N35\r\n" + 
        "88J)65N\r\n" + 
        "9DM)CW4\r\n" + 
        "DSH)DXM\r\n" + 
        "QSK)2WM\r\n" + 
        "6DH)C53\r\n" + 
        "544)K2Z\r\n" + 
        "F65)9QT\r\n" + 
        "1H2)8MY\r\n" + 
        "6CS)F61\r\n" + 
        "SD1)82Q\r\n" + 
        "SW2)C5J\r\n" + 
        "96X)3CF\r\n" + 
        "M8G)4VR\r\n" + 
        "QML)XM8\r\n" + 
        "5C1)8R1\r\n" + 
        "2R9)YNZ\r\n" + 
        "PY5)LFR\r\n" + 
        "TL1)ZKK\r\n" + 
        "HHD)794\r\n" + 
        "TKX)LNB\r\n" + 
        "95C)BVL\r\n" + 
        "9NM)8HJ\r\n" + 
        "YKQ)Z29\r\n" + 
        "YMG)388\r\n" + 
        "ZGV)XTB\r\n" + 
        "6PN)F7C\r\n" + 
        "DNQ)GSQ\r\n" + 
        "6T7)GZZ\r\n" + 
        "W3G)9X3\r\n" + 
        "F5T)KL4\r\n" + 
        "4H2)QBC\r\n" + 
        "HQC)GG4\r\n" + 
        "1N7)GH9\r\n" + 
        "JT2)QNR\r\n" + 
        "ZHD)CTW\r\n" + 
        "3SS)9S4\r\n" + 
        "Q3H)2TB\r\n" + 
        "KXN)NV4\r\n" + 
        "13K)9WV\r\n" + 
        "PP1)VWR\r\n" + 
        "1YJ)BGM\r\n" + 
        "6RC)M6W\r\n" + 
        "NYZ)5P6\r\n" + 
        "HTT)HP1\r\n" + 
        "712)PSR\r\n" + 
        "DP8)N9L\r\n" + 
        "B2R)8N1\r\n" + 
        "4VR)FP5\r\n" + 
        "T3X)FCR\r\n" + 
        "PG9)NFN\r\n" + 
        "25P)D1Q\r\n" + 
        "NFK)CV8\r\n" + 
        "KGJ)G5S\r\n" + 
        "QRL)C4N\r\n" + 
        "BDM)F95\r\n" + 
        "Y1T)5C1\r\n" + 
        "WLX)HX3\r\n" + 
        "12X)9TL\r\n" + 
        "BPD)SZJ\r\n" + 
        "GMP)RHF\r\n" + 
        "W4D)YYS\r\n" + 
        "722)JVQ\r\n" + 
        "JJ4)3FG\r\n" + 
        "3FG)X4Q\r\n" + 
        "ZM6)3G3\r\n" + 
        "MC6)L7Q\r\n" + 
        "DPB)M39\r\n" + 
        "MQF)W28\r\n" + 
        "87V)8ZV\r\n" + 
        "7DG)M3Y\r\n" + 
        "1VN)MFS\r\n" + 
        "9Q6)3C9\r\n" + 
        "7MP)17N\r\n" + 
        "Y5M)Y3X\r\n" + 
        "6N3)LTV\r\n" + 
        "VQ3)W8G\r\n" + 
        "QRK)GD2\r\n" + 
        "LNB)LFL\r\n" + 
        "DKF)RL2\r\n" + 
        "1T5)W95\r\n" + 
        "VZ5)K5V\r\n" + 
        "76Q)W4D\r\n" + 
        "QH2)8JR\r\n" + 
        "2WM)S9C\r\n" + 
        "9X1)V35\r\n" + 
        "KZN)YRP\r\n" + 
        "9X5)T47\r\n" + 
        "FPS)TCH\r\n" + 
        "YRJ)Y6B\r\n" + 
        "67X)SFG\r\n" + 
        "D68)YQ6\r\n" + 
        "YKV)B2L\r\n" + 
        "6PN)7FT\r\n" + 
        "KWW)ZQ6\r\n" + 
        "ZTS)2BS\r\n" + 
        "HG6)2B8\r\n" + 
        "9K1)62W\r\n" + 
        "4YH)J98\r\n" + 
        "RRG)FJW\r\n" + 
        "J98)QK3\r\n" + 
        "LRZ)P76\r\n" + 
        "83Y)GXQ\r\n" + 
        "838)X49\r\n" + 
        "4LB)GC3\r\n" + 
        "2R4)DPB\r\n" + 
        "MC4)31H\r\n" + 
        "M8Z)FKJ\r\n" + 
        "8R1)NDM\r\n" + 
        "GNX)GYF\r\n" + 
        "MFL)DL7\r\n" + 
        "WGD)JSX\r\n" + 
        "SGN)TKX\r\n" + 
        "C2D)P6P\r\n" + 
        "LHH)G31\r\n" + 
        "PN6)959\r\n" + 
        "Q4Q)1CD\r\n" + 
        "3GL)82F\r\n" + 
        "MS5)SPX\r\n" + 
        "7GZ)7MC\r\n" + 
        "JRQ)RWY\r\n" + 
        "51T)C2D\r\n" + 
        "9N6)PR9\r\n" + 
        "CTW)Y54\r\n" + 
        "MJW)LJ7\r\n" + 
        "QBC)PW7\r\n" + 
        "NDM)RD5\r\n" + 
        "K85)KWW\r\n" + 
        "HBS)T66\r\n" + 
        "PC2)H7X\r\n" + 
        "MFS)VF9\r\n" + 
        "4J5)X6P\r\n" + 
        "JP8)GF2\r\n" + 
        "7VZ)C3H\r\n" + 
        "6HK)KVS\r\n" + 
        "BKR)96X\r\n" + 
        "QMF)JT2\r\n" + 
        "XDC)FLD\r\n" + 
        "TG3)XDC\r\n" + 
        "CCQ)CH7\r\n" + 
        "48C)CTS\r\n" + 
        "9WV)1YK\r\n" + 
        "31G)M8Z\r\n" + 
        "RYN)HV3\r\n" + 
        "WC6)9DH\r\n" + 
        "H7C)XT5\r\n" + 
        "36P)SX4\r\n" + 
        "P28)RWX\r\n" + 
        "H7C)L59\r\n" + 
        "P3K)RKB\r\n" + 
        "HP3)MS5\r\n" + 
        "Y1F)X6X\r\n" + 
        "LZV)F4K\r\n" + 
        "6TR)33Y\r\n" + 
        "YQ6)N8D\r\n" + 
        "MMP)6NJ\r\n" + 
        "4R8)J47\r\n" + 
        "9JV)JF2\r\n" + 
        "15R)ZQP\r\n" + 
        "CH7)31G\r\n" + 
        "FJW)1KF\r\n" + 
        "YSV)G5C\r\n" + 
        "LKV)C6M\r\n" + 
        "W28)HP3\r\n" + 
        "33Y)MQF\r\n" + 
        "V35)PN6\r\n" + 
        "24J)6PN\r\n" + 
        "ZJ1)QH2\r\n" + 
        "BGT)S8W\r\n" + 
        "61W)MD5\r\n" + 
        "GZZ)M6B\r\n" + 
        "FCR)427\r\n" + 
        "RD5)WGD\r\n" + 
        "72B)9Q6\r\n" + 
        "62W)51T\r\n" + 
        "82Q)CQH\r\n" + 
        "MZT)TL1\r\n" + 
        "D8M)T2B\r\n" + 
        "R8X)8YD\r\n" + 
        "F1K)9WC\r\n" + 
        "ZL6)3LX\r\n" + 
        "M6K)KTL\r\n" + 
        "GY6)GYN\r\n" + 
        "V8Q)J88\r\n" + 
        "WHH)STN\r\n" + 
        "XCC)WQK\r\n" + 
        "LGC)5JG\r\n" + 
        "S9G)FDZ\r\n" + 
        "LR8)W6M\r\n" + 
        "FC5)HX2\r\n" + 
        "MBC)M6F\r\n" + 
        "JSX)P3K\r\n" + 
        "K5J)Y9T\r\n" + 
        "ZRC)99H\r\n" + 
        "RGR)HHD\r\n" + 
        "QK2)GYY\r\n" + 
        "Y93)8QK\r\n" + 
        "Z5Z)7VQ\r\n" + 
        "DM6)41X\r\n" + 
        "ZQP)KWZ\r\n" + 
        "T4S)8PB\r\n" + 
        "66B)SGZ\r\n" + 
        "2Z3)L28\r\n" + 
        "CR9)ZTW\r\n" + 
        "79G)MFL\r\n" + 
        "M56)X79\r\n" + 
        "JLJ)CJ9\r\n" + 
        "SD7)JZT\r\n" + 
        "KVS)YSV\r\n" + 
        "K2M)869\r\n" + 
        "BX1)371\r\n" + 
        "F4K)1H2\r\n" + 
        "RZQ)MP3\r\n" + 
        "HX2)GLM\r\n" + 
        "3M6)PY5\r\n" + 
        "YY6)M6G\r\n" + 
        "32F)MWS\r\n" + 
        "1JC)SPG\r\n" + 
        "Y54)GQT\r\n" + 
        "1BN)MBC\r\n" + 
        "7MC)9JV\r\n" + 
        "G35)RTC\r\n" + 
        "38H)J68\r\n" + 
        "CFB)ZLH\r\n" + 
        "YYS)81D\r\n" + 
        "J2H)557\r\n" + 
        "L57)N6J\r\n" + 
        "5YR)LLG\r\n" + 
        "SX4)JN2\r\n" + 
        "PMV)44K\r\n" + 
        "ZH2)XSN\r\n" + 
        "QTJ)V8J\r\n" + 
        "5DZ)VZ5\r\n" + 
        "VYL)165\r\n" + 
        "PR9)W41\r\n" + 
        "NLD)61V\r\n" + 
        "TKD)H4G\r\n" + 
        "45M)H25\r\n" + 
        "9PF)WT5\r\n" + 
        "7FT)YM1\r\n" + 
        "LBT)32F\r\n" + 
        "SJS)224\r\n" + 
        "7NW)874\r\n" + 
        "DXZ)SW2\r\n" + 
        "XR2)SLK\r\n" + 
        "TD9)PC2\r\n" + 
        "1X1)WLM\r\n" + 
        "57Y)C1Y\r\n" + 
        "HCF)3GL\r\n" + 
        "7W2)2BB\r\n" + 
        "5RT)6T7\r\n" + 
        "YLZ)DGZ\r\n" + 
        "MBX)7LN\r\n" + 
        "F9G)MJW\r\n" + 
        "88P)8WS\r\n" + 
        "DRM)HCZ\r\n" + 
        "B7Z)BBH\r\n" + 
        "VD9)LKV\r\n" + 
        "MJW)J9N\r\n" + 
        "JYK)5CF\r\n" + 
        "5FJ)6TR\r\n" + 
        "DG4)QML\r\n" + 
        "MTY)55J\r\n" + 
        "NRM)BX1\r\n" + 
        "CRP)1KL\r\n" + 
        "YHP)JNJ\r\n" + 
        "DPH)N4X\r\n" + 
        "ZLH)FNK\r\n" + 
        "QZ7)JTK\r\n" + 
        "W9Y)4P2\r\n" + 
        "ZCQ)HCF\r\n" + 
        "Y9K)MBX\r\n" + 
        "ZGV)F9G\r\n" + 
        "Z96)W9Y\r\n" + 
        "XQT)YTZ\r\n" + 
        "J88)FPS\r\n" + 
        "8DT)FWK\r\n" + 
        "T88)2L9\r\n" + 
        "FCH)ZCZ\r\n" + 
        "HWZ)7PJ\r\n" + 
        "VW3)P5F\r\n" + 
        "X8G)BW9\r\n" + 
        "GZD)VQ3\r\n" + 
        "SPX)LCT\r\n" + 
        "QK3)7MP\r\n" + 
        "31H)1M3\r\n" + 
        "MR9)RGR\r\n" + 
        "JF6)3PF\r\n" + 
        "7GK)JM7\r\n" + 
        "Y41)QK2\r\n" + 
        "54M)1JC\r\n" + 
        "12D)B2R\r\n" + 
        "X77)ZHD\r\n" + 
        "3D6)5J6\r\n" + 
        "X79)ZRC\r\n" + 
        "3HJ)K1M\r\n" + 
        "W9Y)8PW\r\n" + 
        "H59)YLZ\r\n" + 
        "5YF)Z3M\r\n" + 
        "44V)ZGV\r\n" + 
        "GH9)LPP\r\n" + 
        "QTS)BHF\r\n" + 
        "WM1)8RN\r\n" + 
        "LHN)QSG\r\n" + 
        "YSQ)Y9R\r\n" + 
        "1YK)RYN\r\n" + 
        "JQK)QJ9\r\n" + 
        "JYH)VD9\r\n" + 
        "H84)4KZ\r\n" + 
        "8GC)7W2\r\n" + 
        "63N)QTS\r\n" + 
        "9CK)N89\r\n" + 
        "241)RZQ\r\n" + 
        "DBQ)D4H\r\n" + 
        "MTY)12X\r\n" + 
        "TWS)YRD\r\n" + 
        "83H)5YF\r\n" + 
        "LHN)5CM\r\n" + 
        "683)BPV\r\n" + 
        "SLK)WTG\r\n" + 
        "1N7)9HJ\r\n" + 
        "RKB)TGL\r\n" + 
        "2W5)2FR\r\n" + 
        "K5V)ZTD\r\n" + 
        "MZ7)5KW\r\n" + 
        "N8Y)DBX\r\n" + 
        "BBH)WLH\r\n" + 
        "7C3)F44\r\n" + 
        "M39)69L\r\n" + 
        "LV1)R1N\r\n" + 
        "QSK)PY6\r\n" + 
        "ZWN)CX1\r\n" + 
        "427)MTY\r\n" + 
        "DW7)1RY\r\n" + 
        "ZSQ)R5W\r\n" + 
        "6VT)22N\r\n" + 
        "557)2Y7\r\n" + 
        "QGN)P7Z\r\n" + 
        "F65)NYZ\r\n" + 
        "RJ9)QGN\r\n" + 
        "ZCZ)KJ3\r\n" + 
        "Z1S)PKJ\r\n" + 
        "Y4F)TWS\r\n" + 
        "QH7)ZH2\r\n" + 
        "J8X)P5R\r\n" + 
        "2BB)GF4\r\n" + 
        "726)YP6\r\n" + 
        "YK5)7GZ\r\n" + 
        "LTV)7JD\r\n" + 
        "2NN)1ZW\r\n" + 
        "BVS)9CK\r\n" + 
        "361)FRD\r\n" + 
        "T21)712\r\n" + 
        "LVY)W8C\r\n" + 
        "V39)Z1S\r\n" + 
        "2S6)HQC\r\n" + 
        "RWY)MKM\r\n" + 
        "L28)F97\r\n" + 
        "PNB)B7G\r\n" + 
        "HCZ)HWZ\r\n" + 
        "MHT)RST\r\n" + 
        "34X)9SM\r\n" + 
        "KJ3)79F\r\n" + 
        "K8L)8GC\r\n" + 
        "FRD)9T6\r\n" + 
        "KK5)G2K\r\n" + 
        "82F)KYL\r\n" + 
        "5LB)V8Q\r\n" + 
        "21L)46C\r\n" + 
        "MFR)VKC\r\n" + 
        "HMH)7T2\r\n" + 
        "XK9)CBP\r\n" + 
        "ZK3)X8C\r\n" + 
        "FVD)YKV\r\n" + 
        "JTK)CYN\r\n" + 
        "QDJ)3SS\r\n" + 
        "YNZ)DHZ\r\n" + 
        "F7R)7NW\r\n" + 
        "WLH)2T4\r\n" + 
        "1H2)D68\r\n" + 
        "98G)NLD\r\n" + 
        "959)PMV\r\n" + 
        "KMN)61T\r\n" + 
        "GQT)ZTS\r\n" + 
        "LF3)WHH\r\n" + 
        "3C9)J2X\r\n" + 
        "4K2)BJT\r\n" + 
        "R2K)5SJ\r\n" + 
        "W6M)N8P\r\n" + 
        "BJT)P4X\r\n" + 
        "41X)FS6\r\n" + 
        "MK8)KDB\r\n" + 
        "PJ7)HM1\r\n" + 
        "T5G)MHY\r\n" + 
        "8DT)FCH\r\n" + 
        "F9Y)BPT\r\n" + 
        "W8Q)3DD\r\n" + 
        "YQC)BGH\r\n" + 
        "NWN)C17\r\n" + 
        "MD5)Y1F\r\n" + 
        "MHY)QH7\r\n" + 
        "ZMH)NN8\r\n" + 
        "V32)WTX\r\n" + 
        "FK1)ZJ1\r\n" + 
        "SD7)1TM\r\n" + 
        "1TK)T4P\r\n" + 
        "79F)3S8\r\n" + 
        "C1Y)QTL\r\n" + 
        "ZML)PKM\r\n" + 
        "M3Y)2V5\r\n" + 
        "VQ8)ZMH\r\n" + 
        "S9C)M6K\r\n" + 
        "TKD)544\r\n" + 
        "DL7)K8L\r\n" + 
        "BHF)8BC\r\n" + 
        "WT5)NYF\r\n" + 
        "JD3)GNM\r\n" + 
        "GC3)32M\r\n" + 
        "5CF)XV8\r\n" + 
        "B3S)P5J\r\n" + 
        "5L7)5DV\r\n" + 
        "PGN)3JR\r\n" + 
        "2V5)843\r\n" + 
        "8NQ)RHD\r\n" + 
        "W5N)76Q\r\n" + 
        "GF4)QHF\r\n" + 
        "78B)MHT\r\n" + 
        "JZT)GZD\r\n" + 
        "RWX)FLN\r\n" + 
        "FGG)HN9\r\n" + 
        "MP3)B94\r\n" + 
        "F1C)79B\r\n" + 
        "C3H)7WK\r\n" + 
        "WLH)T21\r\n" + 
        "R5W)7VL\r\n" + 
        "6DS)3S6\r\n" + 
        "QNR)271\r\n" + 
        "Y75)95S\r\n" + 
        "K8V)T4J\r\n" + 
        "2DN)RCV\r\n" + 
        "3G3)34X\r\n" + 
        "84Z)V32\r\n" + 
        "2T4)TWG\r\n" + 
        "S26)814\r\n" + 
        "DPF)D8M\r\n" + 
        "N9D)THZ\r\n" + 
        "8S7)2CC\r\n" + 
        "8CX)CLG\r\n" + 
        "4DZ)RBH\r\n" + 
        "42G)DWS\r\n" + 
        "SFN)LZV\r\n" + 
        "P7Z)LTH\r\n" + 
        "G2K)J2H\r\n" + 
        "2L4)5YZ\r\n" + 
        "6S6)GDR\r\n" + 
        "2CC)MZ7\r\n" + 
        "WNX)T9K\r\n" + 
        "DHZ)LVY\r\n" + 
        "WQK)5WJ\r\n" + 
        "LS1)44V\r\n" + 
        "2XL)2GH\r\n" + 
        "X3D)VTB\r\n" + 
        "5KW)PP1\r\n" + 
        "4BH)V39\r\n" + 
        "STV)ZSQ\r\n" + 
        "83D)PH7\r\n" + 
        "VF9)VH9\r\n" + 
        "S8W)6VB\r\n" + 
        "F4B)Y75\r\n" + 
        "VYG)SFY\r\n" + 
        "KTL)45M\r\n" + 
        "LFL)PS5\r\n" + 
        "MWS)JLY\r\n" + 
        "SH3)39L\r\n" + 
        "9DH)61W\r\n" + 
        "MD4)NK9\r\n" + 
        "49C)2W5\r\n" + 
        "7CL)3TL\r\n" + 
        "CBP)2R4\r\n" + 
        "271)K7T\r\n" + 
        "3TL)5L7\r\n" + 
        "ZM1)ZML\r\n" + 
        "W9T)GBS\r\n" + 
        "6FL)LHN\r\n" + 
        "Z7W)1PB\r\n" + 
        "JNJ)XCC\r\n" + 
        "YTZ)6DS\r\n" + 
        "BST)4BW\r\n" + 
        "SZJ)DKF\r\n" + 
        "PTH)2S6\r\n" + 
        "2VH)361\r\n" + 
        "8BC)Q4B\r\n" + 
        "PSR)7WV\r\n" + 
        "4BB)32V\r\n" + 
        "PQL)TJ5\r\n" + 
        "D3X)TVD\r\n" + 
        "HYC)J8X\r\n" + 
        "ZPF)XXY\r\n" + 
        "1RT)BST\r\n" + 
        "Q3H)Q7C\r\n" + 
        "YVJ)ZWN\r\n" + 
        "XPX)1TK\r\n" + 
        "SJS)YK5\r\n" + 
        "22N)N72\r\n" + 
        "JRN)H84\r\n" + 
        "1T5)MD4\r\n" + 
        "XZG)4ZJ\r\n" + 
        "55J)8C7\r\n" + 
        "N8P)GMJ\r\n" + 
        "PSR)1VN\r\n" + 
        "YQV)FGH\r\n" + 
        "KRT)SZQ\r\n" + 
        "CP5)1N7\r\n" + 
        "Q5F)29K\r\n" + 
        "Q5P)QMF\r\n" + 
        "YP5)726\r\n" + 
        "YW9)4SL\r\n" + 
        "R8P)7ZB\r\n" + 
        "1RY)JF6\r\n" + 
        "ZQZ)R8P\r\n" + 
        "7W2)YHP\r\n" + 
        "2B8)SH3\r\n" + 
        "794)H59\r\n" + 
        "BBJ)27J\r\n" + 
        "VJF)S4R\r\n" + 
        "XPT)RV1\r\n" + 
        "7T2)ZXL\r\n" + 
        "GLM)3BF\r\n" + 
        "32M)SS5\r\n" + 
        "9HJ)JG2\r\n" + 
        "8MY)YKL\r\n" + 
        "QMF)JQJ\r\n" + 
        "PK5)CLP\r\n" + 
        "GYF)WY9\r\n" + 
        "G5C)JGL\r\n" + 
        "JG2)K8V\r\n" + 
        "YQC)79G\r\n" + 
        "4PL)L45\r\n" + 
        "32P)BY1\r\n" + 
        "ZDQ)925\r\n" + 
        "W41)G5P\r\n" + 
        "SM2)P87\r\n" + 
        "NBZ)5FJ\r\n" + 
        "814)KZN\r\n" + 
        "NJK)PNB\r\n" + 
        "FMY)NRM\r\n" + 
        "4VZ)CGG\r\n" + 
        "652)YKK\r\n" + 
        "WVB)BY5\r\n" + 
        "C4N)4R8\r\n" + 
        "9BM)87V\r\n" + 
        "9QT)HKS\r\n" + 
        "N6J)6HK\r\n" + 
        "8PW)B4S\r\n" + 
        "LPP)7NS\r\n" + 
        "HCF)DP8\r\n" + 
        "6DK)MC4\r\n" + 
        "4JV)48C\r\n" + 
        "WYH)JTD\r\n" + 
        "4D2)1SQ\r\n" + 
        "C17)MK8\r\n" + 
        "X77)WSM\r\n" + 
        "XTB)PCT\r\n" + 
        "J47)9X5\r\n" + 
        "3Q3)88P\r\n" + 
        "97J)C92\r\n" + 
        "HP1)HG6\r\n" + 
        "4P2)DW7\r\n" + 
        "843)D3X\r\n" + 
        "THZ)D4Q\r\n" + 
        "F44)36P\r\n" + 
        "P5R)WDY\r\n" + 
        "BZP)PJ7\r\n" + 
        "RDF)48T\r\n" + 
        "R17)7WG\r\n" + 
        "FWK)Y4F\r\n" + 
        "39X)JQD\r\n" + 
        "SY2)BDM\r\n" + 
        "DJN)Y93\r\n" + 
        "KTP)RTM\r\n" + 
        "73W)WNX\r\n" + 
        "935)LBT\r\n" + 
        "N2L)5DZ\r\n" + 
        "L7L)5MS\r\n" + 
        "224)785\r\n" + 
        "FDZ)GNX\r\n" + 
        "F3H)5WR\r\n" + 
        "LPB)YSQ\r\n" + 
        "DBV)Y9K\r\n" + 
        "ZKP)97J\r\n" + 
        "FJW)ZM1\r\n" + 
        "MYD)MM5\r\n" + 
        "COM)HM9\r\n" + 
        "SGZ)Q4Q\r\n" + 
        "NK9)4H2\r\n" + 
        "VM4)5G3\r\n" + 
        "Q7C)FPX\r\n" + 
        "FS6)M56\r\n" + 
        "XBR)N8Y\r\n" + 
        "BDL)SML\r\n" + 
        "YRD)HKR\r\n" + 
        "F7C)PRR\r\n" + 
        "388)RY4\r\n" + 
        "HV3)XBR\r\n" + 
        "M9X)NWN\r\n" + 
        "F27)CYL\r\n" + 
        "WDY)SJS\r\n" + 
        "ZR4)5LY\r\n" + 
        "L7Q)YP5\r\n" + 
        "YRP)DY2\r\n" + 
        "HX3)1SD\r\n" + 
        "R9H)PBD\r\n" + 
        "X8D)W3B\r\n" + 
        "Y41)6FM\r\n" + 
        "Z9F)4TR\r\n" + 
        "MM5)66B\r\n" + 
        "SML)38H\r\n" + 
        "NFN)1KN\r\n" + 
        "4W2)ZLV\r\n" + 
        "BZP)9X1\r\n" + 
        "Q7C)5DY\r\n" + 
        "1TM)HKB\r\n" + 
        "VKX)LWG\r\n" + 
        "FCR)F7F\r\n" + 
        "BY1)5J7\r\n" + 
        "THS)LKP\r\n" + 
        "WQK)C19\r\n" + 
        "17N)Y1T\r\n" + 
        "CKH)L57\r\n" + 
        "78P)NV5\r\n" + 
        "GF2)FGG\r\n" + 
        "FGG)SD1\r\n" + 
        "874)KTP\r\n" + 
        "JRR)CFB\r\n" + 
        "4VC)T3X\r\n" + 
        "DGZ)WZC\r\n" + 
        "1CD)83D\r\n" + 
        "XXY)S26\r\n" + 
        "LKH)JD3\r\n" + 
        "K1M)KK5\r\n" + 
        "8YQ)6V7\r\n" + 
        "TKR)VQ8\r\n" + 
        "N7H)ZZP\r\n" + 
        "R1N)F1C\r\n" + 
        "TPW)R2K\r\n" + 
        "JGL)XNJ\r\n" + 
        "5WJ)72B\r\n" + 
        "62W)ZPF\r\n" + 
        "KNY)C7F\r\n" + 
        "SPG)3PC\r\n" + 
        "FNK)NBZ\r\n" + 
        "HKB)NFK\r\n" + 
        "CJ9)9WW\r\n" + 
        "KWZ)M8G\r\n" + 
        "P28)NVF\r\n" + 
        "6V7)MYD\r\n" + 
        "ZYH)JYD\r\n" + 
        "XQT)VFM\r\n" + 
        "99H)9FJ\r\n" + 
        "4ML)GY6\r\n" + 
        "CP5)WM1\r\n" + 
        "X6P)STV\r\n" + 
        "1SQ)KRT\r\n" + 
        "7JD)J2B\r\n" + 
        "3JZ)F7R\r\n" + 
        "65N)QRK\r\n" + 
        "MW7)TFR\r\n" + 
        "2L9)ZDQ\r\n" + 
        "D4H)F9Y\r\n" + 
        "PS5)WTV\r\n" + 
        "G35)6QC\r\n" + 
        "LTH)9MY\r\n" + 
        "DQJ)2VH\r\n" + 
        "SPB)6HB\r\n" + 
        "L9W)L7L\r\n" + 
        "WNL)83H\r\n" + 
        "34G)JLJ\r\n" + 
        "8SL)H75\r\n" + 
        "JVQ)CKH\r\n" + 
        "165)VW3\r\n" + 
        "X4Q)DBQ\r\n" + 
        "VWR)7YW\r\n" + 
        "T9K)JW4\r\n" + 
        "79G)WYH\r\n" + 
        "S5T)K6R\r\n" + 
        "78P)QRX\r\n" + 
        "GZT)447\r\n" + 
        "3S6)4YH\r\n" + 
        "PCT)57Y\r\n" + 
        "39X)W9T\r\n" + 
        "Y9R)5RT\r\n" + 
        "8C7)DNQ\r\n" + 
        "9WC)MNY\r\n" + 
        "785)SFN\r\n" + 
        "RCV)42G\r\n" + 
        "D1Q)Q5P\r\n" + 
        "C4Y)DG4\r\n" + 
        "72G)78B\r\n" + 
        "XHT)S5T\r\n" + 
        "HX3)WTB\r\n" + 
        "JVC)9NM\r\n" + 
        "KMZ)WVB\r\n" + 
        "HN9)5LB\r\n" + 
        "WTV)JP8\r\n" + 
        "8JP)Z5Z\r\n" + 
        "VTB)WHR\r\n" + 
        "BWP)YTK\r\n" + 
        "PY6)DXZ\r\n" + 
        "5G3)2NN\r\n" + 
        "ZXL)3HJ\r\n" + 
        "3ZD)VKX\r\n" + 
        "4ZJ)8RD\r\n" + 
        "GWX)1FD\r\n" + 
        "WDY)4ML\r\n" + 
        "P4X)3D6\r\n" + 
        "JQJ)34G\r\n" + 
        "KNH)Q81\r\n" + 
        "HPR)SG1\r\n" + 
        "RY4)73V\r\n" + 
        "7ZB)BYD\r\n" + 
        "BPT)ZK3\r\n" + 
        "CLG)G7W\r\n" + 
        "3CF)1D1\r\n" + 
        "B5F)21L\r\n" + 
        "Z4Y)FBV\r\n" + 
        "GM9)JRR\r\n" + 
        "D9M)C7J\r\n" + 
        "B4S)ZKP\r\n" + 
        "P5J)32P\r\n" + 
        "T9K)FK1\r\n" + 
        "HXQ)7LT\r\n" + 
        "MSD)88Z\r\n" + 
        "5P6)JRN\r\n" + 
        "M91)JQK\r\n" + 
        "W82)ZSH\r\n" + 
        "WLM)935\r\n" + 
        "DY2)J81\r\n" + 
        "9XJ)4JZ\r\n" + 
        "N72)VM4\r\n" + 
        "T2B)V7B\r\n" + 
        "M6B)2XL\r\n" + 
        "J77)N5J\r\n" + 
        "9W2)T2J\r\n" + 
        "JFL)Q11\r\n" + 
        "FNK)V15\r\n" + 
        "W8G)QRL\r\n" + 
        "T4J)F5T\r\n" + 
        "G5S)F65\r\n" + 
        "G31)LGC\r\n" + 
        "8YD)6CS\r\n" + 
        "838)TWL\r\n" + 
        "CW4)RDF\r\n" + 
        "46C)GM9\r\n" + 
        "HSX)MTZ\r\n" + 
        "447)RJ9\r\n" + 
        "N4X)25P\r\n" + 
        "9FJ)6S6\r\n" + 
        "W8S)ZVM\r\n" + 
        "NN8)N7H\r\n" + 
        "6T7)M9L\r\n" + 
        "CV8)2L4\r\n" + 
        "ZZP)PYZ\r\n" + 
        "HKR)YXC\r\n" + 
        "C28)6VT\r\n" + 
        "FBV)QPZ\r\n" + 
        "WY9)BXH\r\n" + 
        "JF2)GSK\r\n" + 
        "PYR)195\r\n" + 
        "GD2)KY5\r\n" + 
        "1ZW)BKR\r\n" + 
        "CZL)VX9\r\n" + 
        "C7F)VP1\r\n" + 
        "VFM)CYB\r\n" + 
        "MC6)TZP\r\n" + 
        "C75)9BM\r\n" + 
        "GSQ)LHH\r\n" + 
        "J2X)3K1\r\n" + 
        "7CL)JJ4\r\n" + 
        "RHF)MZT\r\n" + 
        "5DV)3CM\r\n" + 
        "5MR)Z68\r\n" + 
        "6HZ)N2L\r\n" + 
        "D39)HYC\r\n" + 
        "D4Q)DV6\r\n" + 
        "2TB)H3R\r\n" + 
        "673)J27\r\n" + 
        "J81)B5F\r\n" + 
        "1D1)JKT\r\n" + 
        "44K)Y8D\r\n" + 
        "8PB)1T5\r\n" + 
        "C92)QZ7\r\n" + 
        "LW8)4TW\r\n" + 
        "3Q4)SGN\r\n" + 
        "FK1)D9Q\r\n" + 
        "ZSH)PK5\r\n" + 
        "BXL)6HZ\r\n" + 
        "FQ5)T5G\r\n" + 
        "KDB)C75\r\n" + 
        "3HJ)LRZ\r\n" + 
        "VCJ)LV4\r\n" + 
        "G7K)4JV\r\n" + 
        "HMP)54M\r\n" + 
        "7PJ)3Q4\r\n" + 
        "GH2)5R2\r\n" + 
        "B1W)DPH\r\n" + 
        "P6P)1YJ\r\n" + 
        "B9S)3JZ\r\n" + 
        "J1Q)NVV\r\n" + 
        "CQH)BWC\r\n" + 
        "48T)FNP\r\n" + 
        "Z29)86W\r\n" + 
        "NNC)LGY\r\n" + 
        "H3R)DPF\r\n" + 
        "CLP)JKB\r\n" + 
        "LLG)8TM\r\n" + 
        "TQQ)7C3\r\n" + 
        "8N1)XR2\r\n" + 
        "D9Q)B3S\r\n" + 
        "GC3)84Z\r\n" + 
        "QPZ)83Y\r\n" + 
        "5DR)JPT\r\n" + 
        "2BS)M2H\r\n" + 
        "F1T)XQT\r\n" + 
        "KYL)SPB\r\n" + 
        "VP1)Q6F\r\n" + 
        "P2H)NJK\r\n" + 
        "CTS)7VZ\r\n" + 
        "J27)YD4\r\n" + 
        "NRM)Z4Y\r\n" + 
        "RTC)M91\r\n" + 
        "7LT)D39\r\n" + 
        "W95)T88\r\n" + 
        "M6W)691\r\n" + 
        "KP3)BBJ\r\n" + 
        "SZJ)HR2\r\n" + 
        "V8J)88J\r\n" + 
        "8VG)S95\r\n" + 
        "R3K)VWT\r\n" + 
        "ZVM)XZG\r\n" + 
        "9MY)6L2\r\n" + 
        "L59)WGP\r\n" + 
        "5WR)LKH\r\n" + 
        "M9L)D2X\r\n" + 
        "JSF)X8D\r\n" + 
        "RGR)K85\r\n" + 
        "H7X)VJF\r\n" + 
        "7KT)Y26\r\n" + 
        "ZK3)PG9\r\n" + 
        "61V)YQC\r\n" + 
        "NYF)8YQ\r\n" + 
        "ZLV)WT4\r\n" + 
        "9X1)L9W\r\n" + 
        "CQK)GH2\r\n" + 
        "C7J)SD7\r\n" + 
        "FG6)15R\r\n" + 
        "K6R)Z9F\r\n" + 
        "SS5)WT1\r\n" + 
        "9X3)LJN\r\n" + 
        "JVQ)2Z3\r\n" + 
        "4BW)JRC\r\n" + 
        "5LY)XPX\r\n" + 
        "LJ7)D9M\r\n" + 
        "LRZ)PYR\r\n" + 
        "JW4)KT5\r\n" + 
        "HM9)LS1\r\n" + 
        "SG1)XHT\r\n" + 
        "HK8)4G3\r\n" + 
        "L45)KNH\r\n" + 
        "1KF)DJN\r\n" + 
        "KXG)TXP\r\n" + 
        "FPX)2DX\r\n" + 
        "DNQ)4K2\r\n" + 
        "DX6)W46\r\n" + 
        "7GH)3ZD\r\n" + 
        "MK8)5MR\r\n" + 
        "RKB)7DG\r\n" + 
        "QHF)X3D\r\n" + 
        "QJ9)5DR\r\n" + 
        "F97)PQL\r\n" + 
        "X6X)2DN\r\n" + 
        "PRR)ZYH\r\n" + 
        "CJ9)HK8\r\n" + 
        "677)MMP\r\n" + 
        "FRD)R3K\r\n" + 
        "13K)TJJ\r\n" + 
        "3PF)3FQ\r\n" + 
        "FGH)XX5\r\n" + 
        "N8D)9W2\r\n" + 
        "4DP)R9H\r\n" + 
        "3JR)YVJ\r\n" + 
        "B5F)VJB\r\n" + 
        "YTH)PJ2\r\n" + 
        "78M)4VZ\r\n" + 
        "PJ2)C28\r\n" + 
        "5DY)R8X\r\n" + 
        "TPW)HPR\r\n" + 
        "TZP)YW9\r\n" + 
        "JRC)4J5\r\n" + 
        "5SJ)XK9\r\n" + 
        "Y6B)67X\r\n" + 
        "B7G)K5J\r\n" + 
        "BGH)MW7\r\n" + 
        "8JR)T2Z\r\n" + 
        "VX9)HQZ\r\n" + 
        "XM8)B9S\r\n" + 
        "MS5)HLP\r\n" + 
        "9S4)4BH\r\n" + 
        "LFR)K2M\r\n" + 
        "5JG)3SP\r\n" + 
        "J2B)Z7W\r\n" + 
        "X49)TG3\r\n" + 
        "7LN)JPC\r\n" + 
        "GXQ)GS4\r\n" + 
        "6L2)TNX\r\n" + 
        "3FG)BDL\r\n" + 
        "T47)X77\r\n" + 
        "RX9)1X1\r\n" + 
        "GYY)KXG\r\n" + 
        "QS4)M9X\r\n" + 
        "Y26)VM9\r\n" + 
        "RTM)9DM\r\n" + 
        "3HZ)12D\r\n" + 
        "KK2)ZM6\r\n" + 
        "68X)N9D\r\n" + 
        "B7G)3M6\r\n" + 
        "DB3)4LB\r\n" + 
        "2DX)RZ9\r\n" + 
        "C19)CQK\r\n" + 
        "NBB)3HZ\r\n" + 
        "8TM)F3H\r\n" + 
        "WT4)4PL\r\n" + 
        "CZL)JYH\r\n" + 
        "15P)KK2\r\n" + 
        "9MV)DRM\r\n" + 
        "TFR)JVC\r\n" + 
        "ZQ6)TVW\r\n" + 
        "Z7W)DQJ\r\n" + 
        "8MW)QSK\r\n" + 
        "XJH)X8G\r\n" + 
        "P5F)NBB\r\n" + 
        "YQN)YMG\r\n" + 
        "F7F)73W\r\n" + 
        "Y3X)652\r\n" + 
        "HM1)Y41\r\n" + 
        "ZTD)TKR\r\n" + 
        "4YK)13K\r\n" + 
        "95J)1FJ\r\n" + 
        "1FJ)5YR\r\n" + 
        "PW7)534\r\n" + 
        "CX1)MFR\r\n" + 
        "DWS)TPW\r\n" + 
        "LFV)N5F\r\n" + 
        "427)P28\r\n" + 
        "K2Z)CP5\r\n" + 
        "V7B)SY2\r\n" + 
        "N8P)NNC\r\n" + 
        "F44)39X\r\n" + 
        "3FQ)2R9\r\n" + 
        "YXC)DM6\r\n" + 
        "ZTW)9XJ\r\n" + 
        "7WG)2Q8\r\n" + 
        "QTL)M6H\r\n" + 
        "F1K)LRD\r\n" + 
        "3BF)THS\r\n" + 
        "T66)FMY\r\n" + 
        "27J)1RT\r\n" + 
        "1KN)BPD\r\n" + 
        "GNM)9PF\r\n" + 
        "MTZ)QWN\r\n" + 
        "QSG)MF2\r\n" + 
        "8T7)683\r\n" + 
        "Z5Z)8S7\r\n" + 
        "8SH)W4F\r\n" + 
        "XX5)BWP\r\n" + 
        "9DH)KGJ\r\n" + 
        "M9X)6N3\r\n" + 
        "TGL)MR9\r\n" + 
        "MQF)FQ5\r\n" + 
        "TS6)6FL\r\n" + 
        "CYN)6DH\r\n" + 
        "195)SAN\r\n" + 
        "STN)WZL\r\n" + 
        "RBH)M8S\r\n" + 
        "73V)WNL\r\n" + 
        "BPV)HMH\r\n" + 
        "8QK)DBV\r\n" + 
        "WY9)JTV\r\n" + 
        "G7W)9N6\r\n" + 
        "TXP)4BB\r\n" + 
        "PH7)WC6\r\n" + 
        "CGG)1BN\r\n" + 
        "JF6)NNR\r\n" + 
        "5MS)DB3\r\n" + 
        "9SM)965\r\n" + 
        "D8L)916\r\n" + 
        "691)7CL\r\n" + 
        "4G3)8MW\r\n" + 
        "6NJ)T4S\r\n" + 
        "7WK)RX9\r\n" + 
        "JLY)Y5M\r\n" + 
        "DBX)J1K\r\n" + 
        "GBS)F4B\r\n" + 
        "HXQ)CRP\r\n" + 
        "WTX)8VG\r\n" + 
        "WGP)YOU\r\n" + 
        "TVW)G7K\r\n" + 
        "M2H)GKG\r\n" + 
        "65N)722\r\n" + 
        "5J7)XPT\r\n" + 
        "THM)78M\r\n" + 
        "QY3)CZL\r\n" + 
        "9SM)ZR4\r\n" + 
        "P76)W8S\r\n" + 
        "BYD)QTJ\r\n" + 
        "JYD)LW8\r\n" + 
        "4G3)W3G\r\n" + 
        "5R2)QS4\r\n" + 
        "2GH)HZ9\r\n" + 
        "LCT)F1K\r\n" + 
        "WSM)YTH\r\n" + 
        "21L)LR8\r\n" + 
        "HR2)W5N\r\n" + 
        "916)7KT\r\n" + 
        "9TL)7GH\r\n" + 
        "N9L)W8Q\r\n" + 
        "VJB)TD9\r\n" + 
        "FLN)838\r\n" + 
        "1SD)LPB\r\n" + 
        "HKS)49C\r\n" + 
        "88Z)YRJ\r\n" + 
        "CYB)68X\r\n" + 
        "CH7)JYK\r\n" + 
        "XV8)4YK\r\n" + 
        "PXJ)SM2\r\n" + 
        "2Q8)8T7\r\n" + 
        "6QC)G9M\r\n" + 
        "BVL)6DK\r\n" + 
        "J1K)FC5\r\n" + 
        "W3B)4DZ\r\n" + 
        "4TW)YQN\r\n" + 
        "HLP)8JP\r\n" + 
        "M8S)S76\r\n" + 
        "YD4)Q5F\r\n" + 
        "48T)GWX\r\n" + 
        "PKM)4W2\r\n" + 
        "86W)FG2\r\n" + 
        "JTD)JSF\r\n" + 
        "VJB)B7Z\r\n" + 
        "ZM6)P2H\r\n" + 
        "G9M)TKD\r\n" + 
        "ZQP)8XQ\r\n" + 
        "TWG)PXJ\r\n" + 
        "8XQ)3Q3\r\n" + 
        "GG4)ZQZ\r\n" + 
        "W4F)FVD\r\n" + 
        "WT1)673\r\n" + 
        "5CM)4D2\r\n" + 
        "K7T)24J\r\n" + 
        "9HJ)8SH\r\n" + 
        "Q6F)VYL\r\n" + 
        "8RD)78P\r\n" + 
        "JG2)6RC\r\n" + 
        "Q6F)BKL\r\n" + 
        "T2Z)KMZ\r\n" + 
        "LR8)KMN\r\n" + 
        "GKG)38F\r\n" + 
        "XT5)8CX\r\n" + 
        "FG2)VCJ\r\n" + 
        "V15)9MV\r\n" + 
        "GBS)4VC\r\n" + 
        "M6G)TQQ\r\n" + 
        "J9N)QDJ\r\n" + 
        "MF2)BVS\r\n" + 
        "BX1)C4Y\r\n" + 
        "1M3)95J\r\n" + 
        "J97)7GK\r\n" + 
        "VWT)PGN\r\n" + 
        "S9G)72G\r\n" + 
        "87D)B1W\r\n" + 
        "PYZ)F1T\r\n" + 
        "ZCZ)W82\r\n" + 
        "WHR)CRV\r\n" + 
        "7GK)63N\r\n" + 
        "JN2)RRG\r\n" + 
        "QRX)HMP\r\n" + 
        "4VR)ZCQ\r\n" + 
        "V8Q)GMP\r\n" + 
        "SFG)RXQ\r\n" + 
        "39L)G35\r\n" + 
        "WZL)DSH\r\n" + 
        "TWL)MSD\r\n";
    // @formatter:on

    public static HashMap<String, Orbit> parse(String input) {
        HashMap<String, Orbit> objects = new HashMap<String, Orbit>();
        objects.put("COM", new Orbit("COM"));

        // add placeholders
        Arrays.stream(input.split("\r\n")).forEach(s -> {
            String orbitting = s.split("\\)")[1];
            objects.put(orbitting, new Orbit(orbitting));
        });

        // set the orbitted pointers
        Arrays.stream(input.split("\r\n")).forEach(s -> {
            String orbitting = s.split("\\)")[1];
            String orbitted = s.split("\\)")[0];
            objects.get(orbitting).setOrbit(objects.get(orbitted));
        });

        return objects;
    }

    static int move(Set<Orbit> orbits, String origin, String destination) {
        // add all links between orbits
        HashMap<String, HashSet<String>> movesFrom = new HashMap<>();
        for (Orbit o : orbits) {
            if (o.orbit != null) {
                if (movesFrom.get(o.id) == null)
                    movesFrom.put(o.id, new HashSet<>());
                if (movesFrom.get(o.orbit.id) == null)
                    movesFrom.put(o.orbit.id, new HashSet<>());
                movesFrom.get(o.id).add(o.orbit.id);
                movesFrom.get(o.orbit.id).add(o.id);
            }
        }

        HashMap<String, Integer> distanceTo = new HashMap<>();
        distanceTo.put(origin, 0);

        // breadth first search to find path to destination
        LinkedList<String> nextMoves = new LinkedList<>();
        movesFrom.get(origin).forEach(dest -> {
            distanceTo.put(dest, 1);
            nextMoves.add(dest);
        });

        while (!nextMoves.isEmpty()) {
            final var pos = nextMoves.pop();
            if (pos.equals(destination))
                break;

            // add moves from here that haven't been seen yet
            int currentDistance = distanceTo.get(pos);
            movesFrom.get(pos).forEach(dest -> {
                if (!distanceTo.containsKey(dest)) {
                    distanceTo.put(dest, currentDistance + 1);
                    nextMoves.add(dest);
                }
            });
        }

        return distanceTo.get(destination);
    }

    public static void main(String[] args) {
        HashMap<String, Orbit> orbits = parse(INPUT);
        int orbitsCount = orbits.values().stream()
                .mapToInt(Orbit::numDirectAndIndirectOrbits).sum();
        System.out.println("Day 6 part 1: " + orbitsCount);

        int distanceToSanta = move(new HashSet<>(orbits.values()),
                orbits.get("YOU").orbit.id, orbits.get("SAN").orbit.id);
        System.out.println("Day 6 part 2: " + distanceToSanta);
    }
}
